export const INPUT_NUMBER = 'INPUT_NUMBER';
export const INPUT_DECIMAL = 'INPUT_DECIMAL';
export const INPUT_OPERATOR = 'INPUT_OPERATOR';
export const INPUT_EQUALS = 'INPUT_EQUALS';
export const CLEAR_DISPLAY = 'CLEAR_DISPLAY';
